name:                09d
version:             0.1.0.0

dependencies:
# lts/20/2.yaml
- base == 4.16.4.0
- vector == 0.12.3.1

ghc-options:
- -threaded
- -O2
- -Wall

library:
  source-dirs:      src

tests:
  09d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 09d
    - hspec    
