name:                11d
version:             0.1.0.0

dependencies:
# lts/20/2.yaml
- base == 4.16.4.0
- vector == 0.12.3.1

ghc-options:
- -O2
- -Wall

executables:
  11d:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 11d



library:
  source-dirs:      src

tests:
  11d-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 11d
    - hspec    
